"""create_api_endpoints_table

Revision ID: 004909dc6f91
Revises: 19497bdfb2e9
Create Date: 2026-06-22 14:24:34.832939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004909dc6f91'
down_revision: Union[str, None] = '19497bdfb2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_endpoints',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.Column('request_body_json', sa.JSON(), nullable=True),
    sa.Column('responses_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'method', 'path', name='uq_api_endpoints_project_method_path')
    )
    op.create_index(op.f('ix_api_endpoints_project_id'), 'api_endpoints', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_endpoints_project_id'), table_name='api_endpoints')
    op.drop_table('api_endpoints')
    # ### end Alembic commands ###
