"""create environment tables

Revision ID: 1869912c614f
Revises: e730124de194
Create Date: 2026-06-22 11:06:49.474731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1869912c614f'
down_revision: Union[str, None] = 'e730124de194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_name'), 'environments', ['name'], unique=True)
    op.create_table('environment_variables',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment_id', 'key', name='uq_environment_variables_env_key')
    )
    op.create_index(op.f('ix_environment_variables_environment_id'), 'environment_variables', ['environment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_environment_variables_environment_id'), table_name='environment_variables')
    op.drop_table('environment_variables')
    op.drop_index(op.f('ix_environments_name'), table_name='environments')
    op.drop_table('environments')
    # ### end Alembic commands ###
